name: openhell
version: 0.0.1
maintainer: Markus Läll <markus.l2ll@gmail.com>
license: MIT
category: Cryptography

dependencies:
- base
- bytestring
- mtl
- optparse-applicative
- cryptonite
- x509
- cryptostore
- pem
- pkcs10
- asn1-encoding
- asn1-types
- memory
- hourglass
- text

_ghc-options: &ghc-options "-Wall -Wno-name-shadowing -O0"

library:
  source-dirs: src
  ghc-options: *ghc-options
  exposed-modules:
  - X509.Certificate
  - X509.Signature
  - X509.Extensions
  - Key

executables:
  openhell:
    source-dirs: exe
    main: Main.hs
    dependencies: openhell
    other-modules:
    - CLI.Key

default-extensions:
- Arrows
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFunctor
- DeriveGeneric
- DerivingVia
- EmptyDataDecls
- ExtendedDefaultRules
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- PolyKinds
- QuasiQuotes
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeFamilies
- TypeInType
- TypeOperators
- TypeSynonymInstances
